my_scoop/my_scoop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from scoops import views

urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='scoops/about.html'),
        name='about'),
    url(r'^contact/$',
        TemplateView.as_view(template_name='scoops/contact.html'), 
        name='contact'),
    url(r'^scoops/', include('scoops.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', admin.site.urls),
]

my_scoop/scoops/urls.py
from django.conf.urls import url

from . import views

app_name = 'scoops'
urlpatterns = [
    # ex: /scoops/13/
    url(r'^(?P<pk>[0-9]+)/$', views.flavor_detail,
        name='flavor_detail'),
    url(r'^(?P<flavor_id>[0-9]+)/add_to_favorites/$', views.add_to_favorites,
        name='add_to_favorites'),
    url(r'^(?P<flavor_id>[0-9]+)/remove_from_favorites/$',
        views.remove_from_favorites, name='remove_from_favorites'),
    url(r'^(?P<flavor_id>[0-9]+)/review_flavor/$',
        views.review_flavor, name='review_flavor'),
]

my_scoop/scoops/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models


class IzzyFlavor(models.Model):
    # Scraped Fields
    flavor_name = models.CharField(max_length=250)
    flavor_description = models.TextField()
    location = models.CharField(max_length=250)

    # Calculated Field
    date_seen = models.DateTimeField(auto_now_add=True)

    # Debug Field
    url = models.URLField(max_length=250)


class FavoriteFlavor(models.Model):
    user = models.ForeignKey(User, unique=False)
    flavor = models.ForeignKey(
        IzzyFlavor, unique=False, on_delete=models.CASCADE)


class FlavorReview(models.Model):
    flavor = models.ForeignKey(IzzyFlavor)
    author = models.ForeignKey(User)
    review_title = models.CharField(max_length=250)
    RATING_CHOICES = (
        (1, "1 Star"),
        (2, "2 Stars"),
        (3, "3 Stars"),
        (4, "4 Stars"),
    )
    flavor_rating = models.IntegerField(choices=RATING_CHOICES)
    review_text = models.TextField()

my_scoop/scoops/forms.py
from django.forms import ModelForm
from .models import FlavorReview


class FlavorReviewForm(ModelForm):
    class Meta:
        model = FlavorReview
        fields = ('review_title', 'flavor_rating', 'review_text')

my_scoop/scoops/views.py
import datetime

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django_tables2 import RequestConfig

from .models import IzzyFlavor, FavoriteFlavor
from .tables import IzzyFlavorTable
from .forms import FlavorReviewForm


def index(request):
    """Uses django_tables2 to render a table of flavors and locations"""
    # get a query set of flavors from today
    table = IzzyFlavorTable(IzzyFlavor.objects.filter(
        date_seen__date=datetime.date.today()))
    # paginate to show 32 flavors per page (1 page per location)
    RequestConfig(request, paginate={'per_page': 32}).configure(table)
    return render(request, 'scoops/index.html', {'table': table})


def flavor_detail(request, pk):
    # get the flavor by primary key
    flavor = IzzyFlavor.objects.get(pk=pk)
    user = request.user    
    
    def is_favorite(flavor, user):
        """Determines if the user has added this flavor to their favorites"""
        try:
            favorite = FavoriteFlavor.objects.filter(
                flavor_id=flavor.id).filter(user_id=user.id)
        except FavoriteFlavor.DoesNotExist, e:
            raise e
        # if the query has a value, then the user has marked this
        # flavor as a favorite    
        if (favorite):
            is_favorite = True
        else:
            is_favorite = False
        # determines whether "add to" or "remove from" favorites is shown    
        return is_favorite            

    return render(request, 'scoops/flavor_detail.html',
                  {'flavor': flavor,
                   'is_favorite': is_favorite(flavor, user)})


def add_to_favorites(request, flavor_id):
    # get the flavor being favorited
    flavor = IzzyFlavor.objects.get(pk=flavor_id)
    # create a new FavoriteFlavor entry and save it
    favorite = FavoriteFlavor(user=request.user, flavor=flavor)
    favorite.save()
    # redirect back to the current flavors list
    return HttpResponseRedirect(reverse('home'))


def remove_from_favorites(request, flavor_id):    
    # get the favorite being removed
    favorites = FavoriteFlavor.objects.filter(
        user_id = request.user.id
        ).filter(flavor_id=flavor_id)
    # loop over the query set and delete the item
    # should only return one
    for favorite in favorites:
        favorite.delete()
    # redirect back to the current flavors list
    return HttpResponseRedirect(reverse('home'))


def review_flavor(request, flavor_id):
    # get the flavor being reviewed 
    flavor = IzzyFlavor.objects.get(pk=flavor_id)
    # if this is a POST request, process the form data
    if request.method == 'POST':
        # populate the form with the submitted data
        form = FlavorReviewForm(request.POST)
        if form.is_valid():
            # create a new review, but don't save it yet
            new_review = form.save(commit=False)
            # we need to add the flavor and user ids to the review
            new_review.flavor = flavor
            new_review.author = request.user
            # now we can save the review
            new_review.save()
            # and send the user back to the flavor detail page
            return redirect('scoops:flavor_detail', pk=flavor.id)
    # if not a POST request, create a blank form
    else:
        form = FlavorReviewForm()

    return render(request, 'scoops/review_flavor.html', {
        'form': form, 'flavor': flavor})    

my_scoop/scoops/templates/scoops/about.html
{% extends 'scoops/base.html' %}
{% block title %}Home - {{ block.super }}{% endblock %}
{% block content %}
    <h1>About Page</h1>
    <p>My Scoop lets you select your favorite Izzy's Ice Cream flavors and received notifications when they are available. You can also review flavors, and get recommendations for other flavors you might like if yours isn't being scooped right now.</p>
{% endblock %}  

my_scoop/scoops/templates/scoops/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}My Scoop{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% block header %}{% endblock %}
</head>
<body>
    <header>
        <h1>My Scoop</h1>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'contact' %}">Contact</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'auth_login' %}">Login</a></li>
                <li><a href="{% url 'registration_register' %}">Register</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>   
    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}
</body>
</html>

my_scoop/scoops/templates/scoops/contact.html
{% extends 'scoops/base.html' %}
{% block title %}Home - {{ block.super }}{% endblock %}
{% block content %}
    <h1>Contact Page</h1>
    <p>If this were a real site there would probably be contact info here.</p>
{% endblock %}  

my_scoop/scoops/templates/scoops/flavor_detail.html
{% extends 'scoops/base.html' %}
{% load render_table from django_tables2 %}
{% block title %}{{ flavor.flavor_name }} - {{ block.super }}{% endblock %}
{% block content %}
    <h1>{{ flavor.flavor_name }}</h1>
    <p>{{ flavor.flavor_description }}</p>
    <p>Last seen: {{ flavor.date_seen }}
    {% if user.is_authenticated %}
        {% if is_favorite %}
        <form action="{% url 'scoops:remove_from_favorites' flavor.id %}"
         method="post">
        {% csrf_token %}
            <input type="submit" value="Remove from Favorites"></input>
        </form>
        {% else %}
        <form action="{% url 'scoops:add_to_favorites' flavor.id %}"
        method="post">
        {% csrf_token %}
            <input type="submit" value="Add to Favorites"></input>
        </form>
        <a href="{% url 'scoops:review_flavor' flavor.id %}">Write a Review!</a>
        {% endif %}
    {% else %}
        <p>Log in or Register to track your favorite Flavors.</p>
    {% endif %}
{% endblock %}  

my_scoop/scoops/templates/scoops/index.html
{% extends 'scoops/base.html' %}
{% load render_table from django_tables2 %}
{% block title %}Home - {{ block.super }}{% endblock %}
{% block content %}
    <h1>Current Flavors</h1>
    {% render_table table %}


{% endblock %}  

my_scoop/scoops/templates/scoops/review_flavor.html
{% extends 'scoops/base.html' %}
{% block title %} Review {{ flavor.flavor_name }} - {{ block.super }}
{% endblock %}
{% block content %}
<h1>Review {{ flavor.flavor_name }}</h1>
<form role="form" action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Submit</button>
</form>
{% endblock %}